name: Playwright Python Tests

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create Virtual Environment
        run: |
          python -m venv .venv

      - name: Install Dependencies
        shell: cmd
        run: |
          call .venv\Scripts\activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m playwright install

      - name: Run Playwright Tests
        shell: cmd
        run: |
          call .venv\Scripts\activate

          if exist reports (
            rmdir /s /q reports
          )

          python -m pytest tests --browser ${{ matrix.browser }} --html=reports\report.html

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Playwright-Report-${{ matrix.browser }}
          path: reports